# Generated by Django 2.1.7 on 2019-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgoodrecipes', '0002_auto_20190318_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('title', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(to='allgoodrecipes.RecipeCategory'),
        ),
    ]
