# Generated by Django 2.1.7 on 2019-03-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgoodrecipes', '0005_auto_20190319_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='short',
            field=models.CharField(default='g', max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
