# Generated by Django 2.1.7 on 2019-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgoodrecipes', '0007_auto_20190319_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, to='allgoodrecipes.RecipeCategory'),
        ),
    ]
