# Generated by Django 2.1.7 on 2019-03-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgoodrecipes', '0008_auto_20190319_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_images'),
        ),
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_images'),
        ),
    ]
