# Generated by Django 2.1.7 on 2019-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allgoodrecipes', '0009_auto_20190319_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tip',
            name='url_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
